version: '3.8'

services:
   mongo:
      image: "mongo"
      ports:
         - "27017:27017"
   server:
      image: 7020548690/veggiebasket_server:v1.0.3
      ports:
         - "8080:8080"
      depends_on:
         - "mongo"
      environment:
         - CONNECTIONSTRING=mongodb://mongo:27017/mern-ecommerce
   app:
      image: 7020548690/veggiebasket_app:v1.0.4
      ports:
         - "3000:3000"
      depends_on:
         - "server"
