version: '3.8'

services:
   mongo:
      image: "mongo"
   server:
      build: ./server
      ports:
         - "8080:8080"
      environment:
         - CONNECTIONSTRING=mongodb://mongo:27017/mern-ecommerce
   app:
      build: ./client
      ports:
         - "3000:3000"